routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
// Route url

Route::get('#', function(){

})->name('none');

Route::get('/', 'DashboardController@dashboardAnalytics')->name('index');

Route::get('/sk-layout-fixed', 'StaterkitController@fixed_layout');

Route::resource('pegawai', 'PegawaiController');
Route::resource('divisi', 'DivisiController');
Route::resource('jabatan', 'JabatanController');
Route::resource('calon-pegawai', 'CalonPegawaiController');
Route::get('calon-pegawai/terima/{calonPegawai}', 'CalonPegawaiController@terima')->name('calon-pegawai.terima');
Route::get('calon-pegawai/tolak/{calonPegawai}', 'CalonPegawaiController@tolak')->name('calon-pegawai.tolak');

Route::resource('absensi', 'AbsensiController');
Route::resource('penggajian', 'PenggajianController');

Route::get('/laporan', 'PenggajianController@laporan')->name('laporan.index');
Route::post('/laporan/cetak', 'PenggajianController@cetakLaporan')->name('laporan.cetak');



app/Divisi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\{Model, SoftDeletes};

class Divisi extends Model
{
    use SoftDeletes;
    protected $table = 'divisi';
}

app/Http/Controllers/DivisiController.php
<?php

namespace App\Http\Controllers;

use App\Divisi;
use Illuminate\Http\Request;

class DivisiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $divisi = Divisi::paginate();
        return view('pages.divisi.index', [
            'pageConfigs' => $this->pageConfigs,
            'divisi' => $divisi
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.divisi.create', [
            'pageConfigs' => $this->pageConfigs
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $divisi = new Divisi;
        $divisi->name = $request->nama;
        $divisi->save();

        return redirect()->route('divisi.index')->with('alert-success', 'Berhasil menambah divisi');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Divisi  $divisi
     * @return \Illuminate\Http\Response
     */
    public function show(Divisi $divisi)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Divisi  $divisi
     * @return \Illuminate\Http\Response
     */
    public function edit(Divisi $divisi)
    {
        return view('pages.divisi.edit', [
            'pageConfigs' => $this->pageConfigs,
            'divisi' => $divisi
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Divisi  $divisi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Divisi $divisi)
    {
        $divisi->name = $request->nama;
        $divisi->save();

        return redirect()->route('divisi.index')->with('alert-success', 'Berhasil mengubah data divisi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Divisi  $divisi
     * @return \Illuminate\Http\Response
     */
    public function destroy(Divisi $divisi)
    {
        $divisi->delete();

        return redirect()->route('divisi.index')->with('alert-success', 'Berhasil menghapus data divisi');
    }
}

resources/views/pages/divisi/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Divisi')

@section('vendor-style')
        <!-- vednor css files -->
        <link rel="stylesheet" href="{{ asset('vendors/css/pickers/pickadate/pickadate.css') }}">
@endsection

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="card">
        <div class="card-header">
            <h4 class="card-title">Tambah Divisi</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form class="form" action="{{ route('divisi.store') }}" method="POST">
                    @csrf
                    <div class="form-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-label-group">
                                    <input type="text" id="nama-divisi" class="form-control" placeholder="Nama Divisi" name="nama">
                                    <label for="nama-divisi">Nama Divisi</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Submit</button>
                                <button type="reset" class="btn btn-outline-warning mr-1 mb-1 waves-effect waves-light">Reset</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
  <!-- Dashboard Analytics end -->
  @endsection

resources/views/pages/divisi/edit.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Divisi')

@section('vendor-style')
        <!-- vednor css files -->
        <link rel="stylesheet" href="{{ asset('vendors/css/pickers/pickadate/pickadate.css') }}">
@endsection

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="card">
        <div class="card-header">
            <h4 class="card-title">Edit Divisi</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form class="form" action="{{ route('divisi.update', $divisi) }}" method="POST">
                    @method('PUT')
                    @csrf
                    <div class="form-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-label-group">
                                    <input type="text" id="nama-divisi" class="form-control" placeholder="Nama Divisi" name="nama" value="{{ $divisi->name }}">
                                    <label for="nama-divisi">Nama Divisi</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Submit</button>
                                <button type="reset" class="btn btn-outline-warning mr-1 mb-1 waves-effect waves-light">Reset</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
  @endsection

resources/views/pages/divisi/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Divisi')

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4 class="mb-0">List Divisi</h4>
              <a href="{{ route('divisi.create') }}" class="btn btn-sm btn-success">Tambah Divisi</a>
            </div>
            <div class="card-content">
              <div class="table-responsive mt-1">
                <table class="table table-hover-animation mb-0">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Divisi</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($divisi as $data)
                    <tr>
                      <td>{{(($divisi->currentPage()-1) * $divisi->perPage()) + $loop->iteration}}</td>
                      <td>{{ $data->name }}</td>
                      <td>
                          <a href="{{ route('divisi.edit', $data) }}" class="btn badge badge-sm badge-warning"> <span class="fa fa-edit"></span></a>
                          <span data-title="{{$data->name}}" href="{{ route('divisi.destroy', $data) }}" class="btn badge badge-sm badge-danger btn-delete"> <span class="fa fa-trash"></span></span>
                      </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan="3" align="center">Tidak ada data</td>
                    </tr>
                    @endforelse
                  </tbody>
                </table>

		            {{ $divisi->links() }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  <form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
  @endsection


@section('myscript')

  <script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');

        Swal.fire({
            title: "Hapus data "+ title +" ?",
            text: "Data yang dihapus tidak dapat dikembalikan !",
            type: "warning",
            showCancelButton: !0,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Yes, delete it!",
            confirmButtonClass: "btn btn-primary",
            cancelButtonClass: "btn btn-danger ml-1",
            buttonsStyling: !1
        }).then(function(t) {
          if(t.value){
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        })
    });
  </script>
@endsection