routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
// Route url

Route::get('#', function(){

})->name('none');

Route::get('/', 'DashboardController@dashboardAnalytics')->name('index');

Route::get('/sk-layout-fixed', 'StaterkitController@fixed_layout');

Route::resource('pegawai', 'PegawaiController');
Route::resource('divisi', 'DivisiController');
Route::resource('jabatan', 'JabatanController');
Route::resource('calon-pegawai', 'CalonPegawaiController');
Route::get('calon-pegawai/terima/{calonPegawai}', 'CalonPegawaiController@terima')->name('calon-pegawai.terima');
Route::get('calon-pegawai/tolak/{calonPegawai}', 'CalonPegawaiController@tolak')->name('calon-pegawai.tolak');

Route::resource('absensi', 'AbsensiController');
Route::resource('penggajian', 'PenggajianController');

Route::get('/laporan', 'PenggajianController@laporan')->name('laporan.index');
Route::post('/laporan/cetak', 'PenggajianController@cetakLaporan')->name('laporan.cetak');



app/Jabatan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\{Model, SoftDeletes};

class Jabatan extends Model
{
    use SoftDeletes;
    protected $table = 'jabatan';
}

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use App\Jabatan;
use Illuminate\Http\Request;

class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jabatan = Jabatan::paginate();
        return view('pages.jabatan.index', [
            'pageConfigs' => $this->pageConfigs,
            'jabatan' => $jabatan
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.jabatan.create', [
            'pageConfigs' => $this->pageConfigs
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $jabatan = new Jabatan;
        $jabatan->name = $request->nama;
        $jabatan->save();

        return redirect()->route('jabatan.index')->with('alert-success', 'Berhasil menambah jabatan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Jabatan  $jabatan
     * @return \Illuminate\Http\Response
     */
    public function show(Jabatan $jabatan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Jabatan  $jabatan
     * @return \Illuminate\Http\Response
     */
    public function edit(Jabatan $jabatan)
    {
        return view('pages.jabatan.edit', [
            'pageConfigs' => $this->pageConfigs,
            'jabatan' => $jabatan
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Jabatan  $jabatan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Jabatan $jabatan)
    {
        $jabatan->name = $request->nama;
        $jabatan->save();

        return redirect()->route('jabatan.index')->with('alert-success', 'Berhasil mengubah data jabatan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Jabatan  $jabatan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Jabatan $jabatan)
    {
        $jabatan->delete();

        return redirect()->route('jabatan.index')->with('alert-success', 'Berhasil menghapus data jabatan');
    }
}

resources/views/pages/jabatan/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Jabatan')

@section('vendor-style')
        <!-- vednor css files -->
        <link rel="stylesheet" href="{{ asset('vendors/css/pickers/pickadate/pickadate.css') }}">
@endsection

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="card">
        <div class="card-header">
            <h4 class="card-title">Tambah Jabatan</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form class="form" action="{{ route('jabatan.store') }}" method="POST">
                    @csrf
                    <div class="form-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-label-group">
                                    <input type="text" id="nama-jabatan" class="form-control" placeholder="Nama Jabatan" name="nama">
                                    <label for="nama-jabatan">Nama Jabatan</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Submit</button>
                                <button type="reset" class="btn btn-outline-warning mr-1 mb-1 waves-effect waves-light">Reset</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
  <!-- Dashboard Analytics end -->
  @endsection

resources/views/pages/jabatan/edit.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Jabatan')

@section('vendor-style')
        <!-- vednor css files -->
        <link rel="stylesheet" href="{{ asset('vendors/css/pickers/pickadate/pickadate.css') }}">
@endsection

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="card">
        <div class="card-header">
            <h4 class="card-title">Edit Jabatan</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form class="form" action="{{ route('jabatan.update', $jabatan) }}" method="POST">
                    @method('PUT')
                    @csrf
                    <div class="form-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-label-group">
                                    <input type="text" id="nama-jabatan" class="form-control" placeholder="Nama Jabatan" name="nama" value="{{ $jabatan->name }}">
                                    <label for="nama-jabatan">Nama Jabatan</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Submit</button>
                                <button type="reset" class="btn btn-outline-warning mr-1 mb-1 waves-effect waves-light">Reset</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
  @endsection

resources/views/pages/jabatan/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Jabatan')

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4 class="mb-0">List Jabatan</h4>
              <a href="{{ route('jabatan.create') }}" class="btn btn-sm btn-success">Tambah Jabatan</a>
            </div>
            <div class="card-content">
              <div class="table-responsive mt-1">
                <table class="table table-hover-animation mb-0">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Jabatan</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($jabatan as $data)
                    <tr>
                      <td>{{(($jabatan->currentPage()-1) * $jabatan->perPage()) + $loop->iteration}}</td>
                      <td>{{ $data->name }}</td>
                      <td>
                          <a href="{{ route('jabatan.edit', $data) }}" class="btn badge badge-sm badge-warning"> <span class="fa fa-edit"></span></a>
                          <span data-title="{{$data->name}}" href="{{ route('jabatan.destroy', $data) }}" class="btn badge badge-sm badge-danger btn-delete"> <span class="fa fa-trash"></span></span>
                      </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan="3" align="center">Tidak ada data</td>
                    </tr>
                    @endforelse
                  </tbody>
                </table>

		            {{ $jabatan->links() }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  <form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
  @endsection


@section('myscript')

  <script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');

        Swal.fire({
            title: "Hapus data "+ title +" ?",
            text: "Data yang dihapus tidak dapat dikembalikan !",
            type: "warning",
            showCancelButton: !0,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Yes, delete it!",
            confirmButtonClass: "btn btn-primary",
            cancelButtonClass: "btn btn-danger ml-1",
            buttonsStyling: !1
        }).then(function(t) {
          if(t.value){
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        })
    });
  </script>
@endsection