routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
// Route url

Route::get('#', function(){

})->name('none');

Route::get('/', 'DashboardController@dashboardAnalytics')->name('index');

Route::get('/sk-layout-fixed', 'StaterkitController@fixed_layout');

Route::resource('pegawai', 'PegawaiController');
Route::resource('divisi', 'DivisiController');
Route::resource('jabatan', 'JabatanController');
Route::resource('calon-pegawai', 'CalonPegawaiController');
Route::get('calon-pegawai/terima/{calonPegawai}', 'CalonPegawaiController@terima')->name('calon-pegawai.terima');
Route::get('calon-pegawai/tolak/{calonPegawai}', 'CalonPegawaiController@tolak')->name('calon-pegawai.tolak');

Route::resource('absensi', 'AbsensiController');
Route::resource('penggajian', 'PenggajianController');

Route::get('/laporan', 'PenggajianController@laporan')->name('laporan.index');
Route::post('/laporan/cetak', 'PenggajianController@cetakLaporan')->name('laporan.cetak');



app/Absensi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\{Model, SoftDeletes};

class Absensi extends Model
{
    use SoftDeletes;
    protected $table = 'absensi';

    public function pegawai()
    {
        return $this->belongsTo(Pegawai::class);
    }

    public function penggajian()
    {
        return $this->hasOne(Gaji::class);
    }
}

app/Http/Controllers/AbsensiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\{Absensi, Pegawai};

class AbsensiController extends Controller
{
    public function index()
    {
        $absensi = Absensi::with('pegawai', 'penggajian')->get();

        return view('pages.absensi.index', [
            'pageConfigs' => $this->pageConfigs,
            'absensi' => $absensi
        ]);
    }

    public function create(Request $request)
    {
        $pegawai = Pegawai::get();
        return view('pages.absensi.create', [
            'pageConfigs' => $this->pageConfigs,
            'pegawai' => $pegawai
        ]);
    }

    public function store(Request $request)
    {
        $cek = Absensi::where('pegawai_id', $request->pegawai_id)
                        ->where('periode', $request->periode)
                        ->count();
        if($cek){
            return redirect()->back()->with('alert-error', 'Data absensi pegawai ini sudah pernah dimasukkan');
        }

        $absensi = new Absensi;
        $absensi->pegawai_id = $request->pegawai_id;
        $absensi->periode = $request->periode;
        $absensi->jml_hadir = $request->jml_hadir;
        $absensi->jml_bolos = $request->jml_bolos;
        $absensi->jml_izin = $request->jml_izin;
        $absensi->jml_sakit = $request->jml_sakit;
        $absensi->jml_cuti = $request->jml_cuti;
        $absensi->jml_sppd = $request->jml_sppd;
        $absensi->save();

        return redirect()->route('absensi.index')->with('alert-success', 'Berhasil menambah data absensi');
    }

    public function edit(Absensi $absensi)
    {
        $pegawai = Pegawai::get();
        return view('pages.absensi.edit', [
            'pageConfigs' => $this->pageConfigs,
            'pegawai' => $pegawai,
            'absensi' => $absensi
        ]);
    }

    public function update(Request $request, Absensi $absensi)
    {
        $cek = Absensi::where('pegawai_id', $request->pegawai_id)
                        ->where('periode', $request->periode)
                        ->where('id', '!=', $absensi->id)
                        ->count();
        if($cek){
            return redirect()->back()->with('alert-error', 'Data absensi pegawai ini sudah pernah dimasukkan');
        }

        $absensi->jml_hadir = $request->jml_hadir;
        $absensi->jml_bolos = $request->jml_bolos;
        $absensi->jml_izin = $request->jml_izin;
        $absensi->jml_sakit = $request->jml_sakit;
        $absensi->jml_cuti = $request->jml_cuti;
        $absensi->jml_sppd = $request->jml_sppd;
        $absensi->save();

        return redirect()->route('absensi.index')->with('alert-success', 'Berhasil mengubah data absensi');
    }

    public function destroy(Absensi $absensi)
    {
        $absensi->delete();

        return redirect()->route('absensi.index')->with('alert-success', 'Berhasil menghapus data absensi');
    }
}

resources/views/pages/absensi/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Absensi')

@section('vendor-style')
        <!-- vednor css files -->
        <link rel="stylesheet" href="{{ asset('vendors/css/pickers/pickadate/pickadate.css') }}">
@endsection

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="card">
        <div class="card-header">
            <h4 class="card-title">Tambah Absensi</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form class="form" action="{{ route('absensi.store') }}" method="POST">
                    @csrf
                    <div class="form-body">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-label-group">
                                    <select id="pegawai" class="form-control" name="pegawai_id">
                                        @foreach ($pegawai as $item)
                                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                                        @endforeach
                                      </select>
                                    <label for="pegawai">Nama Pegawai</label>
                                </div>
                            </div>

                            <div class="col-6">
                                <div class="form-label-group">
                                    <select id="periode" class="form-control" name="periode">
                                            <option value="Januari {{ date('Y') }}">Januari {{ date('Y') }}</option>
                                            <option value="Februari {{ date('Y') }}">Februari {{ date('Y') }}</option>
                                            <option value="Maret {{ date('Y') }}">Maret {{ date('Y') }}</option>
                                            <option value="April {{ date('Y') }}">April {{ date('Y') }}</option>
                                            <option value="Mei {{ date('Y') }}">Mei {{ date('Y') }}</option>
                                            <option value="Juni {{ date('Y') }}">Juni {{ date('Y') }}</option>
                                            <option value="Juli {{ date('Y') }}">Juli {{ date('Y') }}</option>
                                            <option value="Agustus {{ date('Y') }}">Agustus {{ date('Y') }}</option>
                                            <option value="September {{ date('Y') }}">September {{ date('Y') }}</option>
                                            <option value="Oktober {{ date('Y') }}">Oktober {{ date('Y') }}</option>
                                            <option value="November {{ date('Y') }}">November {{ date('Y') }}</option>
                                            <option value="Desember {{ date('Y') }}">Desember {{ date('Y') }}</option>
                                      </select>
                                    <label for="periode">Periode</label>
                                </div>
                            </div>


                            <div class="col-6">
                                <div class="form-label-group">
                                    <input type="text" id="jumlah-hadir" class="form-control" placeholder="Jumlah hadir (hari)" name="jml_hadir">
                                    <label for="jumlah-hadir">Jumlah hadir (hari)</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="text" id="jumlah-sakit" class="form-control" placeholder="Jumlah sakit (hari)" name="jml_sakit">
                                    <label for="jumlah-sakit">Jumlah sakit (hari)</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="text" id="jumlah-bolos" class="form-control" placeholder="Jumlah Bolos (hari)" name="jml_bolos">
                                    <label for="jumlah-bolos">Jumlah Bolos (hari)</label>
                                </div>
                            </div>

                            <div class="col-6">
                                <div class="form-label-group">
                                    <input type="text" id="jumlah-izin" class="form-control" placeholder="Jumlah Izin (hari)" name="jml_izin">
                                    <label for="jumlah-izin">Jumlah Izin (hari)</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="text" id="jumlah-cuti" class="form-control" placeholder="Jumlah Cuti (hari)" name="jml_cuti">
                                    <label for="jumlah-cuti">Jumlah Cuti (hari)</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="text" id="jumlah-sppd" class="form-control" placeholder="Jumlah SPPD (hari)" name="jml_sppd">
                                    <label for="jumlah-sppd">Jumlah SPPD (hari)</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Submit</button>
                                <button type="reset" class="btn btn-outline-warning mr-1 mb-1 waves-effect waves-light">Reset</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
  <!-- Dashboard Analytics end -->
  @endsection

resources/views/pages/absensi/edit.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Absensi')

@section('vendor-style')
        <!-- vednor css files -->
        <link rel="stylesheet" href="{{ asset('vendors/css/pickers/pickadate/pickadate.css') }}">
@endsection

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="card">
        <div class="card-header">
            <h4 class="card-title">Edit Absensi</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form class="form" action="{{ route('absensi.update', $absensi) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-body">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-label-group">
                                    <select id="pegawai" class="form-control" name="pegawai_id" disabled>
                                        @foreach ($pegawai as $item)
                                            <option value="{{ $item->id }}" {{ $absensi->pegawai_id == $item->id ? 'selected' : '' }}>{{ $item->name }}</option>
                                        @endforeach
                                      </select>
                                    <label for="pegawai">Nama Pegawai</label>
                                </div>
                            </div>

                            <div class="col-6">
                                <div class="form-label-group">
                                    <select id="periode" class="form-control" name="periode" disabled>
                                            <option value="Januari {{ date('Y') }}">Januari {{ date('Y') }}</option>
                                            <option value="Februari {{ date('Y') }}">Februari {{ date('Y') }}</option>
                                            <option value="Maret {{ date('Y') }}">Maret {{ date('Y') }}</option>
                                            <option value="April {{ date('Y') }}">April {{ date('Y') }}</option>
                                            <option value="Mei {{ date('Y') }}">Mei {{ date('Y') }}</option>
                                            <option value="Juni {{ date('Y') }}">Juni {{ date('Y') }}</option>
                                            <option value="Juli {{ date('Y') }}">Juli {{ date('Y') }}</option>
                                            <option value="Agustus {{ date('Y') }}">Agustus {{ date('Y') }}</option>
                                            <option value="September {{ date('Y') }}">September {{ date('Y') }}</option>
                                            <option value="Oktober {{ date('Y') }}">Oktober {{ date('Y') }}</option>
                                            <option value="November {{ date('Y') }}">November {{ date('Y') }}</option>
                                            <option value="Desember {{ date('Y') }}">Desember {{ date('Y') }}</option>
                                      </select>
                                    <label for="periode">Periode</label>
                                </div>
                            </div>


                            <div class="col-6">
                                <div class="form-label-group">
                                    <input type="text" id="jumlah-hadir" class="form-control" placeholder="Jumlah hadir (hari)" value="{{ $absensi->jml_hadir }}" name="jml_hadir">
                                    <label for="jumlah-hadir">Jumlah hadir (hari)</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="text" id="jumlah-sakit" class="form-control" placeholder="Jumlah sakit (hari)" value="{{ $absensi->jml_sakit }}" name="jml_sakit">
                                    <label for="jumlah-sakit">Jumlah sakit (hari)</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="text" id="jumlah-bolos" class="form-control" placeholder="Jumlah Bolos (hari)" value="{{ $absensi->jml_bolos }}" name="jml_bolos">
                                    <label for="jumlah-bolos">Jumlah Bolos (hari)</label>
                                </div>
                            </div>

                            <div class="col-6">
                                <div class="form-label-group">
                                    <input type="text" id="jumlah-izin" class="form-control" placeholder="Jumlah Izin (hari)" value="{{ $absensi->jml_izin }}" name="jml_izin">
                                    <label for="jumlah-izin">Jumlah Izin (hari)</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="text" id="jumlah-cuti" class="form-control" placeholder="Jumlah Cuti (hari)" value="{{ $absensi->jml_cuti }}" name="jml_cuti">
                                    <label for="jumlah-cuti">Jumlah Cuti (hari)</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="text" id="jumlah-sppd" class="form-control" placeholder="Jumlah SPPD (hari)" value="{{ $absensi->jml_sppd }}" name="jml_sppd">
                                    <label for="jumlah-sppd">Jumlah SPPD (hari)</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Submit</button>
                                <button type="reset" class="btn btn-outline-warning mr-1 mb-1 waves-effect waves-light">Reset</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
  <!-- Dashboard Analytics end -->
  @endsection

  @section('myscript')
      <script>
          $(function(){
            $("#periode").val("{{$absensi->periode}}");
          })
      </script>
  @endsection

resources/views/pages/absensi/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Absensi Pegawai')

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4 class="mb-0">List Absensi Bulanan </h4>
              <a href="{{ route('absensi.create') }}" class="btn btn-sm btn-success">Tambah Absensi Pegawai</a>
            </div>
            <div class="card-content">
              <div class="table-responsive mt-1">
                <table class="table table-hover-animation mb-0">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Status</th>
                      <th>Nama</th>
                      <th>Periode</th>
                      <th>Divisi</th>
                      <th>Hadir</th>
                      <th>Sakit</th>
                      <th>Bolos</th>
                      <th>Izin</th>
                      <th>Cuti</th>
                      <th>SPPD</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($absensi as $data)
                    <tr>
                      <td>{{(($absensi->currentPage()-1) * $absensi->perPage()) + $loop->iteration}}</td>
                      <td>
                        @if ($data->penggajian)
                        <i class="fa fa-circle font-small-3 text-success mr-50"></i> Sudah
                        @else
                          <i class="fa fa-circle font-small-3 text-danger mr-50"></i> Belum
                        @endif
                      </td>
                      <td>{{ $data->pegawai->name }}</td>
                      <td>{{ $data->periode }}</td>
                      <td>{{ $data->pegawai->divisi->name }}</td>
                      <td>{{ $data->jml_hadir }}</td>
                      <td>{{ $data->jml_sakit }}</td>
                      <td>{{ $data->jml_bolos }}</td>
                      <td>{{ $data->jml_izin }}</td>
                      <td>{{ $data->jml_cuti }}</td>
                      <td>{{ $data->jml_sppd }}</td>
                      <td>
                        @if (!$data->penggajian)
                          <a href="{{ route('absensi.edit', $data) }}" class="btn badge badge-sm badge-warning"> <span class="fa fa-edit"></span></a>
                          <span data-title="{{$data->pegawai->name}}" href="{{ route('absensi.destroy', $data) }}" class="btn badge badge-sm badge-danger btn-delete"> <span class="fa fa-trash"></span></span>
                          <a href="{{ route('penggajian.create') }}?penggajian_id={{$data->id}}" class="btn badge badge-sm badge-info"> <span class="fa fa-dollar"></span></a>
                        @else
                        -
                        @endif

                      </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan="11" align="center">Tidak ada data</td>
                    </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <form action="" method="POST" id="deleteForm">
      @csrf
      @method('DELETE')
      <input type="submit" style="display: none;">
  </form>
  @endsection

@section('myscript')

<script type="text/javascript">
  $('.btn-delete').on('click', function(){
      var href = $(this).attr('href');
      var title = $(this).data('title');

      Swal.fire({
          title: "Hapus data "+ title +" ?",
          text: "Data yang dihapus tidak dapat dikembalikan !",
          type: "warning",
          showCancelButton: !0,
          confirmButtonColor: "#3085d6",
          cancelButtonColor: "#d33",
          confirmButtonText: "Yes, delete it!",
          confirmButtonClass: "btn btn-primary",
          cancelButtonClass: "btn btn-danger ml-1",
          buttonsStyling: !1
      }).then(function(t) {
        if(t.value){
          $('#deleteForm').attr('action', href);
          $('#deleteForm').submit();
        }
      })
  });
</script>
@endsection