routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
// Route url

Route::get('#', function(){

})->name('none');

Route::get('/', 'DashboardController@dashboardAnalytics')->name('index');

Route::get('/sk-layout-fixed', 'StaterkitController@fixed_layout');

Route::resource('pegawai', 'PegawaiController');
Route::resource('divisi', 'DivisiController');
Route::resource('jabatan', 'JabatanController');
Route::resource('calon-pegawai', 'CalonPegawaiController');
Route::get('calon-pegawai/terima/{calonPegawai}', 'CalonPegawaiController@terima')->name('calon-pegawai.terima');
Route::get('calon-pegawai/tolak/{calonPegawai}', 'CalonPegawaiController@tolak')->name('calon-pegawai.tolak');

Route::resource('absensi', 'AbsensiController');
Route::resource('penggajian', 'PenggajianController');

Route::get('/laporan', 'PenggajianController@laporan')->name('laporan.index');
Route::post('/laporan/cetak', 'PenggajianController@cetakLaporan')->name('laporan.cetak');



app/Pegawai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\{Model, SoftDeletes};

class Pegawai extends Model
{
    use SoftDeletes;
    protected $table = 'pegawai';

    public function divisi()
    {
        return $this->belongsTo(Divisi::class);
    }

    public function jabatan()
    {
        return $this->belongsTo(Jabatan::class);
    }
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\{Pegawai, Divisi, Jabatan};
use Illuminate\Http\Request;
use Carbon\Carbon;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pegawai = Pegawai::with('divisi', 'jabatan')->paginate();
        return view('pages.pegawai.index', [
            'pageConfigs' => $this->pageConfigs,
            'pegawai' => $pegawai
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $divisi = Divisi::get();
        $jabatan = Jabatan::get();
        return view('pages.pegawai.create', [
            'pageConfigs' => $this->pageConfigs,
            'divisi' => $divisi,
            'jabatan' => $jabatan
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $pegawai = new Pegawai;
        $pegawai->name = $request->nama;
        $pegawai->nip = $request->nip;
        $pegawai->tempat_lahir = $request->tempat_lahir;
        $pegawai->tanggal_lahir = Carbon::parse($request->tanggal_lahir);
        $pegawai->telepon = $request->telepon;
        $pegawai->email = $request->email;
        $pegawai->alamat = $request->alamat;
        $pegawai->tanggal_masuk = Carbon::parse($request->tanggal_masuk);
        $pegawai->gaji_pokok = $request->gaji_pokok;
        $pegawai->divisi_id = $request->divisi;
        $pegawai->jabatan_id = $request->jabatan;
        $pegawai->save();

        return redirect()->route('pegawai.index')->with('alert-success', 'Berhasil menambah pegawai');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function show(Pegawai $pegawai)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function edit(Pegawai $pegawai)
    {
        $divisi = Divisi::get();
        $jabatan = Jabatan::get();
        return view('pages.pegawai.edit', [
            'pageConfigs' => $this->pageConfigs,
            'pegawai' => $pegawai,
            'divisi' => $divisi,
            'jabatan' => $jabatan
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pegawai $pegawai)
    {
        $pegawai->name = $request->nama;
        $pegawai->nip = $request->nip;
        $pegawai->tempat_lahir = $request->tempat_lahir;
        $pegawai->tanggal_lahir = Carbon::parse($request->tanggal_lahir);
        $pegawai->telepon = $request->telepon;
        $pegawai->email = $request->email;
        $pegawai->alamat = $request->alamat;
        $pegawai->tanggal_masuk = Carbon::parse($request->tanggal_masuk);
        $pegawai->gaji_pokok = $request->gaji_pokok;
        $pegawai->divisi_id = $request->divisi;
        $pegawai->jabatan_id = $request->jabatan;
        $pegawai->save();

        return redirect()->route('pegawai.index')->with('alert-success', 'Berhasil mengubah data pegawai');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pegawai  $pegawai
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pegawai $pegawai)
    {
        $pegawai->delete();

        return redirect()->route('pegawai.index')->with('alert-success', 'Berhasil menghapus data pegawai');
    }
}

resources/views/pages/pegawai/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Pegawai')

@section('vendor-style')
        <!-- vednor css files -->
        <link rel="stylesheet" href="{{ asset('vendors/css/pickers/pickadate/pickadate.css') }}">
@endsection

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="card">
        <div class="card-header">
            <h4 class="card-title">Tambah Pegawai</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form class="form" action="{{ route('pegawai.store') }}" method="POST">
                    @csrf
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="nama-pegawai" class="form-control" placeholder="Nama Pegawai" name="nama">
                                    <label for="nama-pegawai">Nama Pegawai</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="nip" class="form-control" placeholder="N I P" name="nip">
                                    <label for="nip">N I P</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="tempat-lahir" class="form-control" placeholder="Tempat Lahir" name="tempat_lahir">
                                    <label for="tempat-lahir">Tempat Lahir</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="tanggal-lahir" class="form-control tanggal" name="tanggal_lahir" placeholder="Tanggal Lahir">
                                    <label for="tanggal-lahir">Tanggal Lahir</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="telepon" class="form-control" name="telepon" placeholder="No Telepon">
                                    <label for="telepon">No Telepon</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="email" id="email" class="form-control" name="email" placeholder="Email">
                                    <label for="email">Email</label>
                                </div>
                            </div>
                            <div class="col-12">
                              <div class="form-label-group">
                                  <textarea name="alamat" class="form-control" placeholder="Alamat Lengkap"></textarea>
                                  <label for="email">Alamat</label>
                              </div>
                            </div>

                            <div class="col-md-6 col-12">
                              <div class="form-label-group">
                                  <input type="text" id="tanggal-masuk" class="form-control tanggal" name="tanggal_masuk" placeholder="Tanggal Masuk">
                                  <label for="tanggal-masuk">Tanggal Masuk</label>
                              </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="gaji-pokok" class="form-control" name="gaji_pokok" placeholder="Gaji Pokok">
                                    <label for="gaji-pokok">Gaji Pokok</label>
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <select id="divisi" class="form-control" name="divisi">
                                        @foreach ($divisi as $item)
                                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                              </div>
                              <div class="col-md-6 col-12">
                                  <div class="form-label-group">
                                      <select id="jabatan" class="form-control" name="jabatan">
                                        @foreach ($jabatan as $item)
                                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                                        @endforeach
                                      </select>
                                  </div>
                                </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Submit</button>
                                <button type="reset" class="btn btn-outline-warning mr-1 mb-1 waves-effect waves-light">Reset</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
  <!-- Dashboard Analytics end -->
  @endsection
  @section('vendor-script')
        <!-- vednor files -->
        <script src="{{ asset('vendors/js/pickers/pickadate/picker.js') }}"></script>
        <script src="{{ asset('vendors/js/pickers/pickadate/picker.date.js') }}"></script>
  @endsection

  @section('myscript')
      <script>
          $(function(){
            $(".tanggal").pickadate({
                selectYears: !0,
                selectMonths: !0,
                format: "dd mmmm yyyy",
                formatSubmit: "yyyy/mm/dd"
            })
          })
      </script>
  @endsection

resources/views/pages/pegawai/edit.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Pegawai')

@section('vendor-style')
        <!-- vednor css files -->
        <link rel="stylesheet" href="{{ asset('vendors/css/pickers/pickadate/pickadate.css') }}">
@endsection

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="card">
        <div class="card-header">
            <h4 class="card-title">Edit Pegawai</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form class="form" action="{{ route('pegawai.update', $pegawai) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="nama-pegawai" class="form-control" placeholder="Nama Pegawai" value="{{ $pegawai->name }}" name="nama">
                                    <label for="nama-pegawai">Nama Pegawai</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="nip" class="form-control" placeholder="N I P" value="{{ $pegawai->nip }}" name="nip">
                                    <label for="nip">N I P</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="tempat-lahir" class="form-control" placeholder="Tempat Lahir" value="{{ $pegawai->tempat_lahir }}" name="tempat_lahir">
                                    <label for="tempat-lahir">Tempat Lahir</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="tanggal-lahir" class="form-control tanggal" value="{{ $pegawai->tanggal_lahir }}" name="tanggal_lahir" placeholder="Tanggal Lahir">
                                    <label for="tanggal-lahir">Tanggal Lahir</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="telepon" class="form-control" value="{{ $pegawai->telepon }}" name="telepon" placeholder="No Telepon">
                                    <label for="telepon">No Telepon</label>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="email" id="email" class="form-control" value="{{ $pegawai->email }}" name="email" placeholder="Email">
                                    <label for="email">Email</label>
                                </div>
                            </div>
                            <div class="col-12">
                              <div class="form-label-group">
                                  <textarea name="alamat" class="form-control" placeholder="Alamat Lengkap">{{ $pegawai->alamat }}</textarea>
                                  <label for="email">Alamat</label>
                              </div>
                            </div>

                            <div class="col-md-6 col-12">
                              <div class="form-label-group">
                                  <input type="text" id="tanggal-masuk" class="form-control tanggal" value="{{ $pegawai->tanggal_masuk }}" name="tanggal_masuk" placeholder="Tanggal Masuk">
                                  <label for="tanggal-masuk">Tanggal Masuk</label>
                              </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <input type="text" id="gaji-pokok" class="form-control" value="{{ $pegawai->gaji_pokok }}" name="gaji_pokok" placeholder="Gaji Pokok">
                                    <label for="gaji-pokok">Gaji Pokok</label>
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="form-label-group">
                                    <select id="divisi" class="form-control" name="divisi">
                                        @foreach ($divisi as $item)
                                            <option value="{{ $item->id }}" {{ $pegawai->divisi_id == $item->id ? 'selectd' : '' }}>{{ $item->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                              </div>
                              <div class="col-md-6 col-12">
                                  <div class="form-label-group">
                                      <select id="jabatan" class="form-control" name="jabatan">
                                        @foreach ($jabatan as $item)
                                            <option value="{{ $item->id }}" {{ $pegawai->jabatan_id == $item->id ? 'selectd' : '' }}>{{ $item->name }}</option>
                                        @endforeach
                                      </select>
                                  </div>
                                </div>
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">Submit</button>
                                <button type="reset" class="btn btn-outline-warning mr-1 mb-1 waves-effect waves-light">Reset</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
  <!-- Dashboard Analytics end -->
  @endsection
  @section('vendor-script')
        <!-- vednor files -->
        <script src="{{ asset('vendors/js/pickers/pickadate/picker.js') }}"></script>
        <script src="{{ asset('vendors/js/pickers/pickadate/picker.date.js') }}"></script>
  @endsection

  @section('myscript')
      <script>
          $(function(){
            $(".tanggal").pickadate({
                selectYears: !0,
                selectMonths: !0,
                format: "dd mmmm yyyy",
                formatSubmit: "yyyy/mm/dd"
            })
          })
      </script>
  @endsection

resources/views/pages/pegawai/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Pegawai')

  @section('content')
    {{-- Dashboard Analytics Start --}}
    <section id="pegawai">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4 class="mb-0">List Pegawai</h4>
              <a href="{{ route('pegawai.create') }}" class="btn btn-sm btn-success">Tambah Pegawai</a>
            </div>
            <div class="card-content">
              <div class="table-responsive mt-1">
                <table class="table table-hover-animation mb-0">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>NIP</th>
                      <th>Nama</th>
                      <th>Divisi</th>
                      <th>Jabatan</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($pegawai as $data)
                    <tr>
                      <td>{{(($pegawai->currentPage()-1) * $pegawai->perPage()) + $loop->iteration}}</td>
                      <td>{{ $data->nip }}</td>
                      <td>{{ $data->name }}</td>
                      <td>{{ $data->divisi->name }}</td>
                      <td>{{ $data->jabatan->name }}</td>
                      <td>
                          {{-- <a href="" class="btn badge badge-sm badge-info"> <span class="fa fa-eye"></span></a> --}}
                          <a href="{{ route('pegawai.edit', $data) }}" class="btn badge badge-sm badge-warning"> <span class="fa fa-edit"></span></a>
                          <span data-title="{{$data->name}}" href="{{ route('pegawai.destroy', $data) }}" class="btn badge badge-sm badge-danger btn-delete"> <span class="fa fa-trash"></span></span>
                      </td>
                    </tr>
                    @empty
                    <tr>
                      <td colspan="6" align="center">Tidak ada data</td>
                    </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <form action="" method="POST" id="deleteForm">
      @csrf
      @method('DELETE')
      <input type="submit" style="display: none;">
  </form>
  @endsection

@section('myscript')

  <script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');

        Swal.fire({
            title: "Hapus data "+ title +" ?",
            text: "Data yang dihapus tidak dapat dikembalikan !",
            type: "warning",
            showCancelButton: !0,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Yes, delete it!",
            confirmButtonClass: "btn btn-primary",
            cancelButtonClass: "btn btn-danger ml-1",
            buttonsStyling: !1
        }).then(function(t) {
          if(t.value){
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        })
    });
  </script>
@endsection